// ============================================================
// FocusGuard AI — PDF Report Service
// ============================================================

import type { WeeklyReport } from '@/types/tracking';
import { formatDuration } from '@/utils/timeUtils';

/**
 * Generate a weekly report PDF.
 * Uses jsPDF for PDF generation.
 */
export async function generateWeeklyReportPDF(report: WeeklyReport): Promise<Blob> {
  // Dynamic import to avoid loading jsPDF until needed
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Helper functions
  const centerText = (text: string, yPos: number, size: number = 12) => {
    doc.setFontSize(size);
    const textWidth = doc.getTextWidth(text);
    doc.text(text, (pageWidth - textWidth) / 2, yPos);
  };

  const addSection = (title: string) => {
    y += 10;
    doc.setFontSize(14);
    doc.setTextColor(124, 58, 237); // Purple
    doc.text(title, 20, y);
    y += 2;
    doc.setDrawColor(124, 58, 237);
    doc.line(20, y, pageWidth - 20, y);
    y += 8;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
  };

  // Title
  doc.setFontSize(24);
  doc.setTextColor(124, 58, 237);
  centerText('FocusGuard AI', y, 24);
  y += 10;
  doc.setTextColor(100, 100, 100);
  centerText('Weekly Productivity Report', y, 16);
  y += 8;
  doc.setFontSize(10);
  centerText(`${report.weekStart} — ${report.weekEnd}`, y, 10);
  y += 5;

  // Summary Section
  addSection('📊 Overview');
  const summaryData = [
    ['Focus Time', formatDuration(report.totalFocusTime)],
    ['Distraction Time', formatDuration(report.totalDistractionTime)],
    ['Focus Score', `${report.focusScore}/100`],
    ['Sessions Completed', `${report.sessionsCompleted}/${report.sessionsTotal}`],
    ['Completion Rate', `${report.completionRate}%`],
    ['Streak', `${report.streakDays} days`],
  ];

  for (const [label, value] of summaryData) {
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}:`, 25, y);
    doc.setTextColor(0, 0, 0);
    doc.text(value, 90, y);
    y += 6;
  }

  // Top Productive Sites
  if (report.topProductiveSites.length > 0) {
    addSection('✅ Most Productive Sites');
    for (const site of report.topProductiveSites.slice(0, 5)) {
      doc.text(`• ${site.domain} — ${formatDuration(site.totalTime)} (${site.visits} visits)`, 25, y);
      y += 6;
    }
  }

  // Top Distracting Sites
  if (report.topDistractingSites.length > 0) {
    addSection('⚠️ Most Distracting Sites');
    for (const site of report.topDistractingSites.slice(0, 5)) {
      doc.text(`• ${site.domain} — ${formatDuration(site.totalTime)} (${site.visits} visits)`, 25, y);
      y += 6;
    }
  }

  // Daily Breakdown
  addSection('📅 Daily Breakdown');
  for (const day of report.dailyStats) {
    doc.text(
      `${day.date}: Focus ${formatDuration(day.focusTime)}, Score ${day.focusScore}, ${day.completedSessions} sessions`,
      25,
      y
    );
    y += 6;
  }

  // AI Insights
  if (report.aiInsights.length > 0) {
    addSection('🤖 AI Insights');
    for (const insight of report.aiInsights) {
      const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 50);
      doc.text(lines, 25, y);
      y += lines.length * 5 + 2;
    }
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  centerText('Generated by FocusGuard AI — Your Personal Productivity Companion', y, 8);

  return doc.output('blob');
}

/**
 * Download a blob as a file.
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
